/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.duan1.ui;

import com.duan1.dao.YeuCauDaoo;
import com.duan1.entity.YeuCau;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dung8
 */
public class PanelAdminDuyetYeuCau extends javax.swing.JPanel {

    /**
     * Creates new form PanelAdminDuyetYeuCau
     */
    public PanelAdminDuyetYeuCau() {
        initComponents();
        tabsPanel.setSelectedIndex(1);
        load();
        loadDaGui();
        loadDaHuy();
    }
    int row = -1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tabsPanel = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaDuyet = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDagui = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDaHuy = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnXetDuyet = new javax.swing.JButton();
        txtNoiDungChinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        btnHuyYeuCau = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPhanHoi = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JLabel();

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        tblDaDuyet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Noi Dung", "Thời Gian", "Phản Hồi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDaDuyet);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabsPanel.addTab("Đã Duyệt", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        tblDagui.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Nhân Viên", "Nội Dung", "Thời Gian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDagui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaguiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDagui);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabsPanel.addTab("Chưa Đọc", jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        tblDaHuy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title ", "Nội Dung", "Thơi Gian ", "Phản Hồi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblDaHuy);

        jPanel6.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        tabsPanel.addTab("Đã Hủy", jPanel6);

        jPanel3.add(tabsPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Khu Vực Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        btnXetDuyet.setBackground(new java.awt.Color(58, 0, 255));
        btnXetDuyet.setForeground(new java.awt.Color(255, 255, 255));
        btnXetDuyet.setText("Chấp Nhận");
        btnXetDuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXetDuyetActionPerformed(evt);
            }
        });

        txtNoiDungChinh.setEnabled(false);

        jLabel2.setText("Nội dung chính");

        jLabel3.setText("Nội dung ");

        txtNoiDung.setEditable(false);
        txtNoiDung.setColumns(20);
        txtNoiDung.setLineWrap(true);
        txtNoiDung.setRows(5);
        jScrollPane2.setViewportView(txtNoiDung);

        btnHuyYeuCau.setBackground(new java.awt.Color(255, 51, 51));
        btnHuyYeuCau.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyYeuCau.setText("Từ Chối");
        btnHuyYeuCau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyYeuCauActionPerformed(evt);
            }
        });

        txtPhanHoi.setColumns(20);
        txtPhanHoi.setLineWrap(true);
        txtPhanHoi.setRows(5);
        jScrollPane5.setViewportView(txtPhanHoi);

        jLabel4.setText("Phản Hồi Chi tiết");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nhân Viên");

        txtNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoiDungChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXetDuyet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHuyYeuCau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(txtNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiDungChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnHuyYeuCau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXetDuyet))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXetDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXetDuyetActionPerformed
        XetDuyetAdmin();
        clear();
    }//GEN-LAST:event_btnXetDuyetActionPerformed

    private void btnHuyYeuCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyYeuCauActionPerformed
        XetTuChoiAdmin();
        clear();
    }//GEN-LAST:event_btnHuyYeuCauActionPerformed

    private void tblDaguiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaguiMouseClicked
        this.row = tblDagui.getSelectedRow();
        if (this.row > -1) {
            txtNoiDung.setText((String) tblDagui.getValueAt(this.row, 3));
            txtNoiDungChinh.setText((String) tblDagui.getValueAt(this.row, 1));
            txtNhanVien.setText((String) tblDagui.getValueAt(this.row, 2));
        }
    }//GEN-LAST:event_tblDaguiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyYeuCau;
    private javax.swing.JButton btnXetDuyet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane tabsPanel;
    private javax.swing.JTable tblDaDuyet;
    private javax.swing.JTable tblDaHuy;
    private javax.swing.JTable tblDagui;
    private javax.swing.JLabel txtNhanVien;
    private javax.swing.JTextArea txtNoiDung;
    private javax.swing.JTextField txtNoiDungChinh;
    private javax.swing.JTextArea txtPhanHoi;
    // End of variables declaration//GEN-END:variables
 YeuCauDaoo ycdao = new YeuCauDaoo();

    void clear() {
        txtNhanVien.setText("");
        txtNoiDung.setText("");
        txtNoiDungChinh.setText("");
        txtPhanHoi.setText("");
    }

    void load() {
        DefaultTableModel model = (DefaultTableModel) tblDaDuyet.getModel();
        model.setRowCount(0);
        try {
            List<YeuCau> list = ycdao.select();
            for (YeuCau dm : list) {
                Object[] row = {
                    dm.getIdyc(),
                    dm.getTitle(),
                    dm.getNoidung(),
                    dm.getThoigian(),
                    dm.getPhanHoi()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
//            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e.getMessage());
        }
    }

    void loadDaGui() {
        DefaultTableModel model = (DefaultTableModel) tblDagui.getModel();
        model.setRowCount(0);
        try {
            List<YeuCau> list = ycdao.selectDagui();
            for (YeuCau dm : list) {
                Object[] row = {
                    dm.getIdyc(),
                    dm.getTitle(),
                    dm.getNguoithuchien(),
                    dm.getNoidung(),
                    dm.getThoigian(),};
                model.addRow(row);
            }
        } catch (Exception e) {
//            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e.getMessage());
        }
    }

    void loadDaHuy() {
        DefaultTableModel model = (DefaultTableModel) tblDaHuy.getModel();
        model.setRowCount(0);
        try {
            List<YeuCau> list = ycdao.selectDahuy();
            for (YeuCau dm : list) {
                Object[] row = {
                    dm.getIdyc(),
                    dm.getTitle(),
                    dm.getNoidung(),
                    dm.getThoigian(),
                    dm.getPhanHoi()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
//            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e.getMessage());
        }
    }

    void GuiYeuCau() {
        if (txtNoiDung.getText().equals("") || txtNoiDungChinh.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đầy đủ Thông Tin");
        } else {
            ycdao.Insert(txtNoiDungChinh.getText().trim(), txtNoiDung.getText().trim());
            JOptionPane.showMessageDialog(this, "Đã Gửi Yêu Cầu Cho admin");
            loadDaGui();
        }
    }

    void XetDuyetAdmin() {

        if (this.row > -1) {
            int stt = (int) tblDagui.getValueAt(this.row, 0);
            String PhanHoi = txtPhanHoi.getText() + " ";

            ycdao.updateXetDuyet(stt, 1, PhanHoi);
            JOptionPane.showMessageDialog(this, " Thành công !");
            loadDaGui();
            load();
            loadDaHuy();
            tabsPanel.setSelectedIndex(0);

        } else {
            JOptionPane.showMessageDialog(this, "Vui Lòng chọn yêu cầu !");
            loadDaGui();
        }
    }

    void XetTuChoiAdmin() {

        if (this.row > -1) {
            int stt = (int) tblDagui.getValueAt(this.row, 0);
            String PhanHoi = txtPhanHoi.getText() + " ";

            ycdao.updateXetDuyet(stt, 0, PhanHoi);
            JOptionPane.showMessageDialog(this, " Thành công !");
            loadDaGui();
            load();
            loadDaHuy();
            tabsPanel.setSelectedIndex(0);

        } else {
            JOptionPane.showMessageDialog(this, "Vui Lòng chọn yêu cầu !");
            loadDaGui();
        }
    }

}
