/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.duan1.ui;

import com.duan1.dao.HoaDonChiTietDao;
import com.duan1.utils.ButtonEditor;
import com.duan1.utils.ButtonRenderer;
import com.duan1.dao.DoanhMucDao;
import com.duan1.dao.GioHangDao;
import com.duan1.dao.KhoHangDao;
import com.duan1.dao.NhatKyHDDao;
import com.duan1.dao.SanPhamDao;
import com.duan1.dao.ThanhToanDao;
import com.duan1.dao.VoucherDao;
import com.duan1.entity.DoanhMuc;
import com.duan1.entity.GioHang;
import com.duan1.entity.HoaDon;
import com.duan1.entity.HoaDonChiTiet;
import com.duan1.entity.NhatKyHoatDong;
import com.duan1.entity.SanPham;
import com.duan1.entity.Voucher;
import com.duan1.utils.DeleteButtonRenderer;
import com.duan1.utils.DialogHelper;
import com.duan1.utils.ShareHelper;
import com.duan1.utils.TableActionCellEditor;
import com.duan1.utils.TableActionCellRender;
import com.duan1.utils.TableActionEven;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.List;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.SheetCollate;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author dung8
 */
public class ThanhToanFrame extends javax.swing.JInternalFrame implements Runnable, ThreadFactory {

    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private Executor executor = Executors.newSingleThreadExecutor(this);

    /**
     * Creates new form ThanhToanFrame
     */
    public ThanhToanFrame() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        init();

        bangGioHang();
    }
    Boolean checkCam = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMavc = new javax.swing.JTextField();
        cboVoucher = new javax.swing.JComboBox<>();
        txtNguoiLap = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTienTra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtghichu = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtKhachDua = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JPanel();
        btnThanhToan1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cboDoanhMuc1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblgiohang = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        readcode = new javax.swing.JTextField();
        btnControl = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Voucher");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Người Lập HD");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Trạng Thái");

        txtMavc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMavcActionPerformed(evt);
            }
        });

        cboVoucher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã  Áp Dụng", "Không  Tìm Thấy", " " }));

        txtNguoiLap.setEnabled(false);
        txtNguoiLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNguoiLapActionPerformed(evt);
            }
        });

        txtTongTien.setEnabled(false);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Tổng Tiền");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Khách Đưa");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Tiền Trả");

        txtTienTra.setEditable(false);
        txtTienTra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTienTra.setEnabled(false);
        txtTienTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienTraActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Ghi Chú");

        txtghichu.setColumns(20);
        txtghichu.setLineWrap(true);
        txtghichu.setRows(5);
        jScrollPane1.setViewportView(txtghichu);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("VND");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("VND");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("VND");

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachDuaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Giá Trị");

        txtGiaTri.setEditable(false);
        txtGiaTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMavc, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNguoiLap, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGiaTri, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboVoucher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(4, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMavc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cboVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNguoiLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThanhToan.setBackground(new java.awt.Color(255, 204, 102));
        btnThanhToan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThanhToan1.setBackground(new java.awt.Color(255, 204, 102));
        btnThanhToan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThanhToan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/shopping-cart (2).png"))); // NOI18N
        btnThanhToan1.setText("Thanh Toán");
        btnThanhToan1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThanhToan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToan1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnThanhToanLayout = new javax.swing.GroupLayout(btnThanhToan);
        btnThanhToan.setLayout(btnThanhToanLayout);
        btnThanhToanLayout.setHorizontalGroup(
            btnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThanhToan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnThanhToanLayout.setVerticalGroup(
            btnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThanhToan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel13.setBackground(new java.awt.Color(255, 204, 102));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setBackground(new java.awt.Color(255, 204, 102));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/Setting24.png"))); // NOI18N
        jLabel24.setText("Tính tiền");
        jLabel24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton3.setBackground(new java.awt.Color(255, 204, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Chuyển Khoản");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 300, 540));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Sản Phẩm", "Tên Sản Phẩm", "Doanh Mục", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPham);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel23.setText("Tìm Kiếm Theo Mã");

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        jPanel18.setBackground(new java.awt.Color(255, 204, 102));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setBackground(new java.awt.Color(255, 204, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Thêm Sản Phẩm");
        jLabel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21))
        );

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel25.setText("Doanh Mục");

        cboDoanhMuc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDoanhMuc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDoanhMuc1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(cboDoanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboDoanhMuc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel15.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 580, 290));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Giỏ Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblgiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá", "Xóa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblgiohang.setRowHeight(30);
        tblgiohang.setSelectionBackground(new java.awt.Color(51, 204, 0));
        jScrollPane3.setViewportView(tblgiohang);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 250));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 240, 210));

        readcode.setEditable(false);
        jPanel15.add(readcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 170, 30));

        btnControl.setForeground(new java.awt.Color(255, 0, 0));
        btnControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/power-on (1).png"))); // NOI18N
        btnControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlActionPerformed(evt);
            }
        });
        jPanel15.add(btnControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 30, 30));

        btnCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/accept_1.png"))); // NOI18N
        btnCheck.setEnabled(false);
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        jPanel15.add(btnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTienTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienTraActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtNguoiLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNguoiLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNguoiLapActionPerformed

    private void txtMavcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMavcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMavcActionPerformed

    private void cboDoanhMuc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDoanhMuc1ActionPerformed
        fillIdsangtable();
    }//GEN-LAST:event_cboDoanhMuc1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CheckVoucher();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblSanPham.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                this.edit();

            }
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        fillIdSanPhamtable();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void btnControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlActionPerformed
        if (checkCam == false) {

            btnControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/power-on_1.png")));
            checkCam = true;
            initWebcam();
        } else {
            btnControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/duan1/icon/power-on (1).png")));

            checkCam = false;
            webcam.close();
        }

    }//GEN-LAST:event_btnControlActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        fillidSptogiohangQR(readcode.getText());

    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnThanhToan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToan1MouseClicked
        try {
            thanhToan();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnThanhToan1MouseClicked

    private void tblSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPhamMouseEntered

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        TinhTien();
        Color backgroundColor = new Color(255, 204, 102);
        btnThanhToan.setBackground(backgroundColor);
        btnThanhToan1.setForeground(Color.black);

    }//GEN-LAST:event_jLabel24MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        load();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachDuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachDuaActionPerformed

    private void txtGiaTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTriActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        btnChuynKhoan();
        btnThanhToan1.setEnabled(true);
        Color backgroundColor = new Color(255, 204, 102);
        btnThanhToan.setBackground(backgroundColor);
        btnThanhToan1.setForeground(Color.black);

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnControl;
    private javax.swing.JPanel btnThanhToan;
    private javax.swing.JLabel btnThanhToan1;
    private javax.swing.JComboBox<String> cboDoanhMuc1;
    private javax.swing.JComboBox<String> cboVoucher;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField readcode;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTable tblgiohang;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtKhachDua;
    private javax.swing.JTextField txtMavc;
    private javax.swing.JTextField txtNguoiLap;
    private javax.swing.JTextField txtTienTra;
    private javax.swing.JTextField txtTimKiem;
    public static javax.swing.JTextField txtTongTien;
    private javax.swing.JTextArea txtghichu;
    // End of variables declaration//GEN-END:variables
    SanPhamDao daosp = new SanPhamDao();
    DoanhMucDao dmdao = new DoanhMucDao();
    GioHangDao gioHangDao = new GioHangDao();
    ThanhToanDao TTDao = new ThanhToanDao();
    HoaDonChiTietDao hdctDao = new HoaDonChiTietDao();
    KhoHangDao khd = new KhoHangDao();
    VoucherDao vcdao = new VoucherDao();
    NhatKyHDDao nkhdDao = new NhatKyHDDao();
    int index = 0;

    public static void setTien(int tt) {
        txtTongTien.setText(Integer.toString(tt));
    }
    /// bảng Giỏ Hàng
    void bangGioHang() {
        TableActionEven even = new TableActionEven() {
            @Override
            public void onEdit(int row) {
                int rows = tblgiohang.getSelectedRow();
                System.out.println(rows);
                DefaultTableModel model = (DefaultTableModel) tblgiohang.getModel();

                // Kiểm tra xem có hàng được chọn hay không
                if (rows >= 0) {
                    try {
                        int quantity = (int) model.getValueAt(rows, 2);
                        if (quantity > 1) {
                            model.setValueAt(quantity - 1, rows, 2);  // Subtract 1 from the quantity
                        } else {
                            model.setValueAt(1, rows, 2);  // Remove the row if quantity is 1 or less
                        }
                    } catch (ArrayIndexOutOfBoundsException e) {
                        System.out.println("lỏ" + e.getMessage());
                    }
                }

                TongTien();
            }

            @Override
            public void onDelete(int row) {
                if (tblgiohang.isEditing()) {
                    tblgiohang.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model = (DefaultTableModel) tblgiohang.getModel();
                model.removeRow(row);
                TongTien();
            }
        };
        try {
            tblgiohang.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender());
            tblgiohang.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditor(even));

        } catch (Exception e) {
            System.out.println(e.getMessage()
            );
        }
    }

    void init() {
        this.load();
        this.fillComboBoxList();
        txtNguoiLap.setText(ShareHelper.USER.getUserName());
        btnThanhToan1.setEnabled(false);
        btnThanhToan.setBackground(Color.white);

    }

    void load() {
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        try {
            List<SanPham> list = daosp.selectThanhToan();
            for (SanPham dm : list) {
                Object[] row = {
                    dm.getIDSanPham(),
                    dm.getTenSanPham(),
                    dm.getIDDoanhMuc(),
                    dm.getGia(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    void fillIdsangtable() {
        DoanhMuc dm1 = (DoanhMuc) cboDoanhMuc1.getSelectedItem();//lay duoc doi tuong danh muc

        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        try {
            List<SanPham> list = daosp.findById(dm1.getIDDoanhMuc());
            for (SanPham dm : list) {
                Object[] row = {
                    dm.getIDSanPham(),
                    dm.getTenSanPham(),
                    dm.getIDDoanhMuc(),
                    dm.getGia(),};
                model.addRow(row);
            }
        } catch (Exception e) {

        }
    }

    void fillIdSanPhamtable() {

        String masp = txtTimKiem.getText();
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        try {

            List<SanPham> list = daosp.findByIdSP(masp);
            for (SanPham dm : list) {
                Object[] row = {
                    dm.getIDSanPham(),
                    dm.getTenSanPham(),
                    dm.getIDDoanhMuc(),
                    dm.getGia(),};
                model.addRow(row);
            }
        } catch (Exception e) {

        }
    }

    void fillComboBoxList() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDoanhMuc1.getModel();
        model.removeAllElements();
        try {
            List<DoanhMuc> list = dmdao.select();
            for (DoanhMuc dm : list) {
                model.addElement(dm);
            }

            cboDoanhMuc1.setRenderer(new DefaultListCellRenderer() {
                @Override
                public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value instanceof DoanhMuc) {
                        DoanhMuc doanhMuc = (DoanhMuc) value;
                        setText(doanhMuc.getTenDoanhMuc()); // Hiển thị tên danh mục
                    }
                    return this;
                }
            });

            cboDoanhMuc1.setSelectedIndex(0);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    void edit() {
        try {
            String masp = (String) tblSanPham.getValueAt(this.index, 0);

            fillidSptogiohang(masp);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    void fillidSptogiohang(String masp) {
        boolean check = true;
        DefaultTableModel model = (DefaultTableModel) tblgiohang.getModel();
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            String value = (String) model.getValueAt(i, 0);
            if (value.equals(masp)) {
                check = false;
                int quantity = (int) model.getValueAt(i, 2);
                model.setValueAt(quantity + 1, i, 2);
                break;
            }
        }

        if (check) {

            try {
                GioHang gh = gioHangDao.select(masp);

//                tblgiohang.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
//                tblgiohang.getColumnModel().getColumn(4).setCellEditor(new ButtonEditor(new JCheckBox(), tblgiohang,tblgiohang.getSelectedRow()));
                Object[] row = {
                    gh.getIDSanPham(),
                    gh.getTenSanPham(),
                    1,
                    gh.getGia(), //                    "Xóa"
                };
                model.addRow(row);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }

        TongTien();

    }

    void editQR() {
        try {
            String maspqr = (String) readcode.getText();

            fillidSptogiohang(maspqr);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    void fillidSptogiohangQR(String maspqr) {
        //idsp tensp - 1 - gia
        boolean check = true;
        DefaultTableModel model = (DefaultTableModel) tblgiohang.getModel();
        int rowCount = model.getRowCount();

        for (int i = 0; i < rowCount; i++) {
            String value = (String) model.getValueAt(i, 0);
            if (value.equals(maspqr)) {
                check = false;
                int quantity = (int) model.getValueAt(i, 2);
                model.setValueAt(quantity + 1, i, 2);
                break;
            }
        }

        if (check) {
            try {
                GioHang gh = gioHangDao.select(maspqr);
//                tblgiohang.getColumnModel().getColumn(4).setCellRenderer(new ButtonRenderer());
//                tblgiohang.getColumnModel().getColumn(4).setCellEditor(new ButtonEditor(new JCheckBox(), tblgiohang, tblgiohang.getSelectedRow()));

                Object[] row = {
                    gh.getIDSanPham(),
                    gh.getTenSanPham(),
                    1,
                    gh.getGia(), //                    "Xóa"
                };
                model.addRow(row);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }

        readcode.setText("");
        btnCheck.setEnabled(false);
        TongTien();
    }

    // QRCode
    private void initWebcam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);
        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);
        jPanel17.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 200));
        executor.execute(this);
    }

    @Override
    public void run() {
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
//                Logger.getLogger(DangNhapJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            Result result = null;
            BufferedImage image = null;
            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }
            LuminanceSource source;
            BinaryBitmap bitmap;

            try {
                source = new BufferedImageLuminanceSource(image);
                bitmap = new BinaryBitmap(new HybridBinarizer(source));
                result = new MultiFormatReader().decode(bitmap);
            } catch (Exception ex) {

            }
            if (result != null) {
                readcode.setText(result.getText());
                btnCheck.setEnabled(true);

            }

        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }

    void TongTien() {
        try {
            int tong = 0;
            DefaultTableModel model = (DefaultTableModel) tblgiohang.getModel();
            int rowCount = model.getRowCount();

            for (int i = 0; i < rowCount; i++) {
                int col2Value = (int) model.getValueAt(i, 2);
                int col3Value = (int) model.getValueAt(i, 3);
                int product = col2Value * col3Value;
                tong += product;
            }

            setTien(tong);
        } catch (Exception e) {
            System.out.println("lỗi hàm tổng tiền ");
        }
    }

    void TinhTien() {
        String strTienKhach = txtKhachDua.getText();
        String strTongTien = txtTongTien.getText();
        String strVoCher = txtGiaTri.getText();
        boolean check = true;
        try {
            int tienKhach = Integer.parseInt(strTienKhach);
            int tongTien = Integer.parseInt(strTongTien);

            if (tienKhach < tongTien || tienKhach <= 0) {
                JOptionPane.showMessageDialog(this, "Tiền khách đưa Thiếu hoặc nhỏ hơn 1");
                check = false;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tiền Phải là số");
            check = false;
        }
        if (strVoCher.isEmpty()) {
            strVoCher = "0";  // sử dụng giá trị mặc định khi strVoCher không có giá trị nhập vào
        }

        if (check) {
            int tienKhach = Integer.parseInt(strTienKhach);
            int tongTien = Integer.parseInt(strTongTien);
            int giamgia = Integer.parseInt(strVoCher);
            int tienThoi = tienKhach - tongTien - giamgia;
            txtTienTra.setText(Integer.toString(tienThoi));
        }

    }

    HoaDon getForm() {
        HoaDon hd = new HoaDon();
        if (txtMavc.getText().equals("")) {
            hd.setMaVoucher(0);
        } else {
            try {
                int mavc = Integer.parseInt(txtMavc.getText());
                hd.setMaVoucher(mavc);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Mã chỉ tồn tại ở dạng số !");
            }

        }
        hd.setNguoiThucHien(ShareHelper.USER.getUserName());
        hd.setTongTien(Integer.parseInt(txtTongTien.getText()));
        hd.setTienKhachDua(Integer.parseInt(txtKhachDua.getText()));
        hd.setTienThoi(Integer.parseInt(txtTienTra.getText()));
        hd.setThoiGian(new Timestamp(System.currentTimeMillis()));
        hd.setGhichu(txtghichu.getText());
        return hd;
    }

    void getModelGioHang(int idHoaDon) {
        boolean check = true;
        DefaultTableModel modelTableGioHang = (DefaultTableModel) tblgiohang.getModel();
        int idHd = idHoaDon;
        for (int i = 0; i < modelTableGioHang.getRowCount(); i++) {

            String idSp = (String) modelTableGioHang.getValueAt(i, 0);
            int quantity = (int) modelTableGioHang.getValueAt(i, 2);
            int price = (int) modelTableGioHang.getValueAt(i, 3);
            // viết câu lệnh insert hóa đơn chi tiét tại đây
            HoaDonChiTiet hdct = new HoaDonChiTiet();
            hdct.setIDHoaDon(idHd);
            hdct.setIDSanPham(idSp);
            hdct.setSoLuong(quantity);
            hdct.setGia(price);
            hdctDao.insertHoaDonChiTiet(hdct);
            int kq = khd.insertTT(idSp, quantity);
            if (kq == 4 || kq == 0 || kq == 5) {
                modelTableGioHang.removeRow(i);
               
                JOptionPane.showMessageDialog(this, "Số lượng Sản phẩm không đủ hoặc đã hết ! ");
                check = false;
            }

        }
        
        
        if (check) {
            this.Amthamh();
            JOptionPane.showMessageDialog(this, "Thanh toán thành công ! ");

            insertNhatKy(idHoaDon);
            modelTableGioHang.setRowCount(0);
            clearfrom();
        }else{
             TTDao.delete(idHd);
        }

    }

    void Amthamh() {
        try {
            String filepath = "F:\\DownLoad\\Lib\\amthanh.wav";
            AudioInputStream aui = AudioSystem.getAudioInputStream(new File(filepath).getAbsoluteFile());
            try {
                Clip clip = AudioSystem.getClip();
                clip.open(aui);
                clip.start();
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }

    void thanhToan() throws SQLException {
        //lấy thong tin từ form hóa đơn
        int idHoaDon = TTDao.insertHoaDon(getForm());
        if (idHoaDon > 0) {
            getModelGioHang(idHoaDon);

        } else {
            JOptionPane.showMessageDialog(this, "Thêm mới hóa đơn thất bại");
        }

    }

    void clearfrom() {
        txtTienTra.setText("");
        txtghichu.setText("");
        txtTongTien.setText("");
        txtKhachDua.setText("");

    }

    // Check voucher 
    void CheckVoucher() {
        String maVoucher = txtMavc.getText();
        try {
            int maVc = Integer.parseInt(maVoucher);
            Voucher foundVoucher = vcdao.findById(maVc);

            if (foundVoucher != null) {
                txtGiaTri.setText(Integer.toString(foundVoucher.getGiaTri()));
                cboVoucher.setSelectedIndex(0); // Chọn tùy chọn "Đã ápụng" trong combobox
            } else {
                JOptionPane.showMessageDialog(this, "Mã Vocher Không Tồn tại Hoặc Đã Hết");
                cboVoucher.setSelectedIndex(1); // Chọn tùy chọn "Không tìmấy mã voucher" trong combobox
            }
        } catch (NumberFormatException e) {
            cboVoucher.setSelectedItem("Mã voucher không hợp lệ"); // Chọn ty chọn "Mã voucher không hợp lệ" trong combobox

        }
    }

    // xủa lý code NhatKyHoatDong
    NhatKyHoatDong getFromHD(int idHoaDon) {
        NhatKyHoatDong nkhd = new NhatKyHoatDong();
        int idHd = idHoaDon;
        nkhd.setNguoiThucHien(ShareHelper.USER.getUserName());
        nkhd.setMoTa("Nhân Viên :" + ShareHelper.USER.getUserName() + " (" + ShareHelper.USER.getTenTK() + ") " + "Đã Khởi Tạo Hóa Đơn Mới Có Mã: " + idHd + " Với Tổng Tiền Là: " + txtTongTien.getText());
        nkhd.setThoiGian(new Timestamp(System.currentTimeMillis()));
        nkhd.setTrangThai(true);
        return nkhd;
    }

    void insertNhatKy(int idHoaDon) {
        NhatKyHoatDong model = getFromHD(idHoaDon);

        try {
            nkhdDao.insert(model);

            DialogHelper.alert(this, "Đã Thêm Vào Nhật Ký!");
        } catch (Exception e) {

        }

    }
    void btnChuynKhoan(){
    txtKhachDua.setText(txtTongTien.getText());
    txtghichu.setText("Khách Chuyển Khoản ");
    txtTienTra.setText("0");
    }

}
